name: release
on:
  push:
    tags:
    - v*.*.*

jobs:
  release:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/setup-go@v5
      id: go
      with:
        check-latest: true
        go-version-file: go.mod

    - uses: actions/checkout@v4

    - name: Build
      env:
        GO111MODULE: on
        GOPATH: /home/runner/work/
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        export TAGNAME=$(jq --raw-output .ref "$GITHUB_EVENT_PATH" | sed -e "s/refs\/tags\///")
        echo "========================================================="
        echo "DEBUG:" $TAGNAME
        echo "========================================================="
        make cross
        echo "========================================================="
        echo "DEBUG: ls pkg/"
        ls pkg/
        echo "========================================================="
        go get -u github.com/tcnksm/ghr
        $GOPATH/bin/ghr -n ${TAGNAME} -b "ʕ◔ϖ◔ʔ Release ${TAGNAME}" -draft ${TAGNAME} pkg/

